### ISSUE TITLE
bower error

### ISSUE THREAD

**Issue by dmitrymar** [gdangelo/react-starter#2]
I run `npm install` successfully but when I run `bower install` I got this error. Please advise. Thanks. 
    bower bootstrap#~3.3.6      not-cached git://github.com/twbs/bootstrap.git#~3.3.6
    bower bootstrap#~3.3.6         resolve git://github.com/twbs/bootstrap.git#~3.3.6
    bower bootstrap#~3.3.6         ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/twbs/bootstrap.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.129]: errno=Operation timed out

**Comment by gdangelo** [comment]
This error is not related to the react-starter repository itself. It is more likely a problem with bower when trying to fetch dependencies. It seems similar to the following issue : [Bower #689](https://github.com/bower/bower/issues/689)
